// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package header

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Tdata struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=Addr,proto3" json:"Addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tdata) Reset()         { *m = Tdata{} }
func (m *Tdata) String() string { return proto.CompactTextString(m) }
func (*Tdata) ProtoMessage()    {}
func (*Tdata) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *Tdata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tdata.Unmarshal(m, b)
}
func (m *Tdata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tdata.Marshal(b, m, deterministic)
}
func (m *Tdata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tdata.Merge(m, src)
}
func (m *Tdata) XXX_Size() int {
	return xxx_messageInfo_Tdata.Size(m)
}
func (m *Tdata) XXX_DiscardUnknown() {
	xxx_messageInfo_Tdata.DiscardUnknown(m)
}

var xxx_messageInfo_Tdata proto.InternalMessageInfo

func (m *Tdata) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Tdata) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type Verify struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Verify) Reset()         { *m = Verify{} }
func (m *Verify) String() string { return proto.CompactTextString(m) }
func (*Verify) ProtoMessage()    {}
func (*Verify) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

func (m *Verify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Verify.Unmarshal(m, b)
}
func (m *Verify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Verify.Marshal(b, m, deterministic)
}
func (m *Verify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Verify.Merge(m, src)
}
func (m *Verify) XXX_Size() int {
	return xxx_messageInfo_Verify.Size(m)
}
func (m *Verify) XXX_DiscardUnknown() {
	xxx_messageInfo_Verify.DiscardUnknown(m)
}

var xxx_messageInfo_Verify proto.InternalMessageInfo

func (m *Verify) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*Tdata)(nil), "header.Tdata")
	proto.RegisterType((*Verify)(nil), "header.Verify")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xcd, 0x4f, 0x49,
	0xcd, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcb, 0x48, 0x4d, 0x4c, 0x49, 0x2d, 0x52,
	0xd2, 0xe7, 0x62, 0x0d, 0x49, 0x49, 0x2c, 0x49, 0x14, 0x12, 0xe2, 0x62, 0xf1, 0x48, 0x2c, 0xce,
	0x90, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x41, 0x62, 0x8e, 0x29, 0x29, 0x45, 0x12,
	0x4c, 0x10, 0x31, 0x10, 0x5b, 0x49, 0x85, 0x8b, 0x2d, 0x2c, 0xb5, 0x28, 0x33, 0xad, 0x52, 0x48,
	0x8a, 0x8b, 0xa3, 0x20, 0xb1, 0xb8, 0xb8, 0x3c, 0xbf, 0x28, 0x05, 0xaa, 0x0b, 0xce, 0x37, 0x32,
	0xe7, 0x62, 0x0e, 0x0a, 0x70, 0x16, 0x32, 0xe0, 0xe2, 0x74, 0xce, 0xcf, 0xcd, 0x2d, 0xcd, 0xcb,
	0x2c, 0x49, 0x15, 0xe2, 0xd3, 0x83, 0xd8, 0xa9, 0x07, 0xd1, 0x2f, 0xc5, 0x0b, 0xe3, 0x83, 0x1d,
	0xa0, 0xc4, 0xa0, 0xc1, 0x68, 0xc0, 0x98, 0xc4, 0x06, 0x76, 0x9e, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0xd8, 0x98, 0xc9, 0xee, 0xad, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RPCClient is the client API for RPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RPCClient interface {
	Communite(ctx context.Context, opts ...grpc.CallOption) (RPC_CommuniteClient, error)
}

type rPCClient struct {
	cc *grpc.ClientConn
}

func NewRPCClient(cc *grpc.ClientConn) RPCClient {
	return &rPCClient{cc}
}

func (c *rPCClient) Communite(ctx context.Context, opts ...grpc.CallOption) (RPC_CommuniteClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RPC_serviceDesc.Streams[0], "/header.RPC/Communite", opts...)
	if err != nil {
		return nil, err
	}
	x := &rPCCommuniteClient{stream}
	return x, nil
}

type RPC_CommuniteClient interface {
	Send(*Verify) error
	Recv() (*Tdata, error)
	grpc.ClientStream
}

type rPCCommuniteClient struct {
	grpc.ClientStream
}

func (x *rPCCommuniteClient) Send(m *Verify) error {
	return x.ClientStream.SendMsg(m)
}

func (x *rPCCommuniteClient) Recv() (*Tdata, error) {
	m := new(Tdata)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RPCServer is the server API for RPC service.
type RPCServer interface {
	Communite(RPC_CommuniteServer) error
}

// UnimplementedRPCServer can be embedded to have forward compatible implementations.
type UnimplementedRPCServer struct {
}

func (*UnimplementedRPCServer) Communite(srv RPC_CommuniteServer) error {
	return status.Errorf(codes.Unimplemented, "method Communite not implemented")
}

func RegisterRPCServer(s *grpc.Server, srv RPCServer) {
	s.RegisterService(&_RPC_serviceDesc, srv)
}

func _RPC_Communite_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RPCServer).Communite(&rPCCommuniteServer{stream})
}

type RPC_CommuniteServer interface {
	Send(*Tdata) error
	Recv() (*Verify, error)
	grpc.ServerStream
}

type rPCCommuniteServer struct {
	grpc.ServerStream
}

func (x *rPCCommuniteServer) Send(m *Tdata) error {
	return x.ServerStream.SendMsg(m)
}

func (x *rPCCommuniteServer) Recv() (*Verify, error) {
	m := new(Verify)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _RPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "header.RPC",
	HandlerType: (*RPCServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Communite",
			Handler:       _RPC_Communite_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "model.proto",
}
